name: tik_tok_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  injectable: ^2.3.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.6
  injectable_generator: ^2.4.1
  dartx: ^1.2.0
  dio: ^5.4.0
  connectivity_plus: ^2.3.8
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.4
  quiver: ^3.2.1
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
